export const alphabetArray = [
    { id: 'a', words: ['apple', 'apricot', 'avocado', 'almond'] },
    { id: 'b', words: ['ball', 'banana', 'butterfly', 'broccoli'] },
    { id: 'c', words: ['cat', 'carrot', 'cupcake', 'cheese'] },
    { id: 'd', words: ['dog', 'duck', 'dragon', 'drum'] },
    { id: 'e', words: ['elephant', 'eggplant', 'eagle', 'eucalyptus'] },
    { id: 'f', words: ['fox', 'flower', 'fire', 'fish'] },
    { id: 'g', words: ['goat', 'grape', 'guitar', 'galaxy'] },
    { id: 'h', words: ['hat', 'heart', 'horse', 'hamburger'] },
    { id: 'i', words: ['ice cream', 'island', 'igloo', 'insect'] },
    { id: 'j', words: ['jellyfish', 'jacket', 'jungle', 'juice'] },
    { id: 'k', words: ['kangaroo', 'key', 'kite', 'kiwi'] },
    { id: 'l', words: ['lion', 'lemon', 'lighthouse', 'leaf'] },
    { id: 'm', words: ['monkey', 'moon', 'mountain', 'mushroom'] },
    { id: 'n', words: ['nest', 'notebook', 'ninja', 'nut'] },
    { id: 'o', words: ['octopus', 'orange', 'owl', 'ocean'] },
    { id: 'p', words: ['panda', 'pizza', 'parrot', 'pear'] },
    { id: 'q', words: ['queen', 'quilt', 'quokka', 'quasar'] },
    { id: 'r', words: ['rabbit', 'rainbow', 'rocket', 'rose'] },
    { id: 's', words: ['sun', 'star', 'snake', 'strawberry'] },
    { id: 't', words: ['turtle', 'tree', 'tiger', 'telescope'] },
    { id: 'u', words: ['umbrella', 'unicorn', 'ukulele', 'underwater'] },
    { id: 'v', words: ['volcano', 'violin', 'vegetable', 'vampire'] },
    { id: 'w', words: ['whale', 'watermelon', 'wizard', 'windmill'] },
    { id: 'x', words: ['xylophone', 'x-ray', 'xenon', 'xerox'] },
    { id: 'y', words: ['yak', 'yellow', 'yogurt', 'yo-yo'] },
    { id: 'z', words: ['zebra', 'zucchini', 'zipper', 'zero'] },
  ];
  
  